# version: "3.10"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres-pgvector
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123123}
      POSTGRES_DB: ${POSTGRES_DB:-test}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=vector
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile # 루트의 Dockerfile 사용 (FastAPI 빌드)
    container_name: snack-api
    restart: always
    ports:
      - "8000:8000" # FastAPI 포트 노출
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app


volumes:
  postgres_data: