create table if not exists snack
(
    id                     bigint generated by default as identity
        constraint pk_snack
            primary key,
    created_by             varchar(255),
    created_at             timestamp,
    modified_by            varchar(255),
    modified_at            timestamp,
    barcode                varchar(255),
    snack_type             varchar(255),
    name                   varchar(255),
    company                varchar(255),
    total_serving_size     varchar(255),
    thumbnail_url          varchar(255),
    main_image_url         varchar(255),
    allergy_list           jsonb,
    safe_food_mark_list    jsonb,
    total_serving_size_num double precision
);

create unique index idx_snack_barcode
    on snack (barcode);

create table if not exists snack_item
(
    id            bigint generated by default as identity
        constraint pk_snackitem
            primary key,
    created_by    varchar(255),
    created_at    timestamp,
    modified_by   varchar(255),
    modified_at   timestamp,
    snack_id      bigint
        constraint fk_snackitem_on_snackid
            references snack,
    item_name     varchar(255),
    service_unit  varchar(255),
    nutrient_list jsonb,
    calorie       integer,
    serving_size  jsonb
);

create table if not exists snack_additive
(
    id                bigint generated by default as identity
        constraint pk_snackadditive
            primary key,
    created_by        varchar(255),
    created_at        timestamp,
    modified_by       varchar(255),
    modified_at       timestamp,
    korean_name       varchar(255),
    english_name      varchar(255),
    main_use_list     jsonb,
    grade             varchar(255),
    description       varchar(2048),
    stability_message varchar(2048),
    simple_name_list  jsonb,
    is_main_use_type  boolean default false not null
);

create table if not exists map_snack_item_additive
(
    id                bigint generated by default as identity
        constraint pk_mapsnackitemadditive
            primary key,
    created_by        varchar(255),
    created_at        timestamp,
    modified_by       varchar(255),
    modified_at       timestamp,
    snack_item_id     bigint not null,
    snack_additive_id bigint not null
);

create index idx_map_snack_item_additive_snack_item_id
    on map_snack_item_additive (snack_item_id);

-- 인덱스 추가
CREATE INDEX IF NOT EXISTS idx_snack_allergy_list_gin
ON public.snack
USING GIN (allergy_list);